function datosImc() {
    return data = [{
            identificacion: "10305060",
            nombres: "Daniel Rodriguez",
            correo: "daniel.rodrigue@gamil.com",
            edad: 26,
            estatura: 178,
            peso: 61,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "4251455",
            nombres: "Predro Mojica",
            correo: "pedro.mogica@gamil.com",
            edad: 20,
            estatura: 165,
            peso: 85,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "5684552",
            nombres: "Jorge Cardoso",
            correo: "jorge.cardozo@gamil.com",
            edad: 24,
            estatura: 160,
            peso: 67,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "8547552",
            nombres: "Jaisson Villamil",
            correo: "jaison.villamil@gamil.com",
            edad: 19,
            estatura: 158,
            peso: 75,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "64785412",
            nombres: "Julian Martinez",
            correo: "julian.martinez@gamil.com",
            edad: 22,
            estatura: 188,
            peso: 71,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "789654",
            nombres: "Daniela Rodriguez",
            correo: "daniela.rodriguez@gamil.com",
            edad: 18,
            estatura: 154,
            peso: 40,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "8547854",
            nombres: "Juan Sanchez",
            correo: "juan.sanchez@gamil.com",
            edad: 19,
            estatura: 162,
            peso: 50,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "8547562",
            nombres: "Maria Guzman",
            correo: "maria.guzman@gamil.com",
            edad: 18,
            estatura: 154,
            peso: 43,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "8547625",
            nombres: "Juanita Velasques",
            correo: "juanita.velasques@gamil.com",
            edad: 24,
            estatura: 150,
            peso: 54,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "5241365",
            nombres: "Paola Espinosa",
            correo: "paola.espinosa@gamil.com",
            edad: 28,
            estatura: 158,
            peso: 50,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "3256412",
            nombres: "Daniel Romero",
            correo: "daniel.romero@gamil.com",
            edad: 29,
            estatura: 172,
            peso: 70,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "85745698",
            nombres: "Camilo Rairan",
            correo: "camilo.rairan@gamil.com",
            edad: 31,
            estatura: 164,
            peso: 50,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "10305060",
            nombres: "Daniel Rodriguez",
            correo: "daniel.rodrigue@gamil.com",
            edad: 26,
            estatura: 178,
            peso: 61,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "4251455",
            nombres: "Predro Mojica",
            correo: "pedro.mogica@gamil.com",
            edad: 20,
            estatura: 165,
            peso: 85,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "5684552",
            nombres: "Jorge Cardoso",
            correo: "jorge.cardozo@gamil.com",
            edad: 24,
            estatura: 160,
            peso: 67,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "8547552",
            nombres: "Jaisson Villamil",
            correo: "jaison.villamil@gamil.com",
            edad: 19,
            estatura: 158,
            peso: 75,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "64785412",
            nombres: "Julian Martinez",
            correo: "julian.martinez@gamil.com",
            edad: 22,
            estatura: 188,
            peso: 71,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "789654",
            nombres: "Daniela Rodriguez",
            correo: "daniela.rodriguez@gamil.com",
            edad: 18,
            estatura: 154,
            peso: 40,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "8547854",
            nombres: "Juan Sanchez",
            correo: "juan.sanchez@gamil.com",
            edad: 19,
            estatura: 162,
            peso: 50,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "8547562",
            nombres: "Maria Guzman",
            correo: "maria.guzman@gamil.com",
            edad: 18,
            estatura: 154,
            peso: 43,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "8547625",
            nombres: "Juanita Velasques",
            correo: "juanita.velasques@gamil.com",
            edad: 24,
            estatura: 150,
            peso: 54,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "5241365",
            nombres: "Paola Espinosa",
            correo: "paola.espinosa@gamil.com",
            edad: 28,
            estatura: 158,
            peso: 50,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "3256412",
            nombres: "Daniel Romero",
            correo: "daniel.romero@gamil.com",
            edad: 29,
            estatura: 172,
            peso: 70,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        },
        {
            identificacion: "85745698",
            nombres: "Camilo Rairan",
            correo: "camilo.rairan@gamil.com",
            edad: 31,
            estatura: 164,
            peso: 50,
            imc: 0,
            descripcion: "",
            clasificacion: 0
        }
    ]
}